name: CI – IaC
on:
  push:
    paths:
      - 'infrastructure/**'
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Init & Validate
        run: |
          cd infrastructure
          terraform init
          terraform validate
      - name: Tfsec Scan
        run: tfsec infrastructure
      - name: Terraform Apply
        run: terraform apply -auto-approve
