name: CI – IaC

on:
  push:
    branches: [ main ]          # run only on pushes to main
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Init & Validate
        run: |
          cd /home/cloud-user/cloudshell-user/cm-app/infrastructure/
          terraform init
          terraform validate
      - name: Tfsec Scan
        run: tfsec .
      - name: Terraform Apply
        run: terraform apply -auto-approve

