 name: CI – IaC

 on:
   push:
     branches: [ main ]

 jobs:
   terraform:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3

+      # ──────────────────────────────────────────────────
+      # Install Terraform on the runner
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: "1.5.7"    # or your preferred version
+      # ──────────────────────────────────────────────────

       - name: Populate infrastructure folder
         uses: actions/checkout@v3
         with:
           path: infrastructure

       - name: Terraform Init & Validate
         working-directory: infrastructure
         run: |
-          terraform init
-          terraform validate
+          terraform init
+          terraform validate

       - name: tfsec Scan
         working-directory: infrastructure
         run: tfsec .

       - name: Terraform Apply
         working-directory: infrastructure
         run: terraform apply -auto-approve

