# File: .github/workflows/ci-iac.yml
name: CI – IaC

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # ── Step 1: Checkout the full repo (app+infra) into ./repo
      - name: Checkout all code
        uses: actions/checkout@v3
        with:
          path: repo
          fetch-depth: 0

      # ── Step 2: Re‑checkout the SAME repo into ./infrastructure
      - name: Populate infrastructure folder
        uses: actions/checkout@v3
        with:
          path: infrastructure

      # ── Step 3: Run Terraform inside that infra folder
      - name: Terraform Init & Validate
        working-directory: infrastructure
        run: |
          terraform init
          terraform validate

      - name: Tfsec Scan
        working-directory: infrastructure
        run: tfsec .

      - name: Terraform Apply
        working-directory: infrastructure
        run: terraform apply -auto-approve

