name: CI – IaC

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        # all `run:` steps execute inside ./infrastructure
        working-directory: infrastructure

    steps:
      # ─── 1) Checkout your repo (app + infra) into ./repo ────────────────────────
      - name: Checkout all code
        uses: actions/checkout@v3
        with:
          path: repo
          fetch-depth: 0

      # ─── 2) Second checkout of the SAME repo into ./infrastructure ─────────────
      - name: Populate infrastructure folder
        uses: actions/checkout@v3
        with:
          path: infrastructure

      # ─── 3) Install Terraform ───────────────────────────────────────────────────
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      # ─── 4) Terraform Init & Validate ─────────────────────────────────────────
      - name: Terraform Init & Validate
        run: |
          terraform init
          terraform validate

      # ─── 5) Install & run tfsec scan ───────────────────────────────────────────
      - name: Install and run tfsec
        run: |
          curl -sSL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh \
            | bash
          tfsec .

      # ─── 6) Terraform Apply ────────────────────────────────────────────────────
      - name: Terraform Apply
        run: terraform apply -auto-approve

